version: '3.8'

services:
  # ===================================================================
  # CONTENEDOR DE BASE DE DATOS
  # ===================================================================
  gourmetconnect-db:
    image: mongodb/mongodb-community-server:8.0.26-ubi8-slim
    container_name: gourmetconnect-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "SecurePass2026!"

  # ===================================================================
  # CONTENEDOR DE LA API (SPRING BOOT)
  # ===================================================================
  gourmetconnect-api:
    build: .
    container_name: gourmetconnect-api-container
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Inyectamos exactamente las variables que el .properties está esperando leer
      SPRING_DATA_MONGODB_HOST: "gourmetconnect-db"
      SPRING_DATA_MONGODB_PORT: "27017"
      SPRING_DATA_MONGODB_USERNAME: "admin"
      SPRING_DATA_MONGODB_PASSWORD: "SecurePass2026!"
      SPRING_DATA_MONGODB_DATABASE: "gourmetconnect"
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: "admin"
    depends_on:
      - gourmetconnect-db

volumes:
  mongo_data:
    driver: local