# ===================================================================
# CONFIGURACIÓN GENERAL DE LA APLICACIÓN
# ===================================================================
spring.application.name=GourmetConnectApi

# ===================================================================
# CONFIGURACIÓN DE INFRAESTRUCTURA - MONGODB (Sintaxis Spring Boot 4.x)
# ===================================================================
# Definición dinámica del Host: Usa la variable de entorno 'MONGO_HOST'
# provista por Docker; si no existe, por defecto aplica 'localhost' para el IDE.
spring.mongodb.uri=mongodb://${MONGO_HOST:localhost}:27017/gourmetconnect_db

# Inicialización automática de índices basados en las anotaciones @Document
spring.data.mongodb.auto-index-creation=true

# ===================================================================
# CONFIGURACIÓN DE DOCUMENTACIÓN DE ENDPOINTS - SWAGGER / OPENAPI
# ===================================================================
# Ruta de acceso para la interfaz gráfica de Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Ruta para la generación de la documentación base en formato JSON/YAML
springdoc.api-docs.path=/api-docs


